// Generate src/mathjax/fonts/tex_smp.cr from mathjax-full's svg TeXFont:
// per-variant input codepoint -> math-alphanumeric (SMP) codepoint.
// Run: node tools/gen_smp.js
const fs = require("fs");
const path = require("path");
const { TeXFont } = require(path.join(__dirname, "..", "dataset/oracle/node_modules/mathjax-full/js/output/svg/fonts/tex.js"));
const f = new TeXFont();

const out = [];
out.push("# GENERATED by tools/gen_smp.js from mathjax-full svg TeXFont variants (Apache-2.0).");
out.push("# mathvariant -> { input codepoint -> math-alphanumeric codepoint }.");
out.push("# Only entries where the variant remaps a plain codepoint to an SMP one.");
out.push("module MathJax::Fonts::TexSmp");
out.push("  SMP = {");
let n = 0;
for (const name of Object.keys(f.variant).sort()) {
  const chars = f.variant[name] && f.variant[name].chars;
  if (!chars) continue;
  const entries = [];
  for (const k of Object.keys(chars)) {
    const cp = +k;
    const smp = (chars[k][3] || {}).smp;
    if (smp && smp !== cp) entries.push([cp, smp]);
  }
  if (!entries.length) continue;
  out.push(`  ${JSON.stringify(name)} => {`);
  let line = "    ";
  for (const [cp, smp] of entries) {
    const piece = cp + " => " + smp + ", ";
    if (line.length + piece.length > 110) {
      out.push(line.replace(/\s+$/, ""));
      line = "    ";
    }
    line += piece;
    n++;
  }
  if (line.trim()) out.push(line.replace(/\s+$/, ""));
  out.push("  },");
}
out.push("  }");
out.push("end");
fs.writeFileSync(path.join(__dirname, "..", "src/mathjax/fonts/tex_smp.cr"), out.join("\n") + "\n");
console.log("variants with remaps, entries:", n);
