// Generate src/mathjax/fonts/tex_opclass.cr from mathjax-full's
// OperatorDictionary: operator char -> texClass per form.
// Run: node tools/gen_opclass.js   (from the repo root; needs
// dataset/oracle/node_modules).
const fs = require("fs");
const path = require("path");
const O = require(path.join(__dirname, "..", "dataset/oracle/node_modules/mathjax-full/js/core/MmlTree/OperatorDictionary.js"));
const t = O.OPTABLE;

const out = [];
out.push("# GENERATED by tools/gen_opclass.js from mathjax-full OperatorDictionary (Apache-2.0).");
out.push("# Operator text -> texClass (ORD=0 OP=1 BIN=2 REL=3 OPEN=4 CLOSE=5 PUNCT=6 INNER=7).");
out.push("# Keys are operator texts; multi-char operators like \"<=\" are included.");
out.push("module MathJax::Fonts::TexOpClass");
let n = 0;
for (const form of ["infix", "prefix", "postfix"]) {
  const tbl = t[form];
  out.push("  " + form.toUpperCase() + " = {");
  let line = "    ";
  for (const k of Object.keys(tbl).sort((a, b) => a.codePointAt(0) - b.codePointAt(0))) {
    const piece = JSON.stringify(k) + " => " + tbl[k][2] + ", ";
    if (line.length + piece.length > 110) {
      out.push(line.replace(/\s+$/, ""));
      line = "    ";
    }
    line += piece;
    n++;
  }
  if (line.trim()) out.push(line.replace(/\s+$/, ""));
  out.push("  }");
}
out.push("end");
fs.writeFileSync(path.join(__dirname, "..", "src/mathjax/fonts/tex_opclass.cr"), out.join("\n") + "\n");
console.log("entries:", n);
